[package]
edition = "2021"
name = "reaper-levitanus"
version = "0.0.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rea-rs = {workspace = true, features = ["egui-baseview"]}
rea-rs-low = {workspace = true}
rea-rs-macros = {workspace = true}

env_logger = {workspace = true}
log = {workspace = true}

anyhow = {workspace = true}
autopilot = {workspace = true}
dyn-clone = {workspace = true}
fraction = {workspace = true, features = ["with-serde-support"]}
itertools = {workspace = true}
lazy_static = {workspace = true}
open = "3.2.0"
path-absolutize = {workspace = true}
regex = {workspace = true}
serde = {workspace = true, features = ["derive"]}
serde_json = {workspace = true}
strum = {workspace = true, features = ["derive"]}
thiserror = {workspace = true}

int-enum = "1.1.2"
url = "2.5.0"
uuid = {version = "1.8.0", features = ["v4"]}

eframe = {version = "0.31", default-features = false, features = [
  "accesskit", # Make egui compatible with screen readers. NOTE: adds a lot of dependencies.
  "default_fonts", # Embed the default egui fonts.
  "glow", # Use the glow rendering backend. Alternative: "wgpu".
  "persistence", # Enable restoring app state when restarting the app.
  "wayland", # To support Linux (and CI)
  "x11",
]}
egui = "0.31"

[lib]
crate-type = ["lib"]
name = "reaper_levitanus"
