[package]
edition = "2021"
name = "reaper-levitanus"
version = "0.0.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rea-rs = {workspace = true}
rea-rs-low = {workspace = true}
rea-rs-macros = {workspace = true}

# musical-note = {workspace = true}

env_logger = {workspace = true}
log = {workspace = true}

fraction = {workspace = true, features=["with-serde-support"]}
itertools = {workspace = true}
open = "3.2.0"
serde = {workspace = true, features = ["derive"]}
thiserror = {workspace = true}
regex = {workspace = true}
lazy_static = {workspace = true}
dyn-clone = {workspace = true}
strum = {workspace = true, features=["derive"]}

# native:
# [target.'cfg(not(target_arch = "wasm32"))'.dependencies]
# tracing-subscriber = "0.3"

# [dev-dependencies]
# once_cell = "1.16"

[lib]
crate-type = ["lib"]
name = "reaper_levitanus"
