name: build and test Linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - uses: ConorMacBride/install-package@v1
      with:
        apt: ffmpeg
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --workspace
    - name: Run tests
      run: RUST_LOG=debug cargo test