name: build and test Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: ConorMacBride/install-package@v1
      with:
        choco: ffmpeg
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --workspace
    - name: Run tests
      run: cargo test
