name: Publish Release
on:
  push:
    tags:
      - '*'
env:
  CARGO_TERM_COLOR: always

jobs:

  linux:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - run: cargo build --all --release --verbose
    - run: mv target/release/libreaper_levitanus_plugin.so target/release/reaper_levitanus_plugin.so
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "target/release/reaper_levitanus_plugin.so"
        bodyFile: "body.md"
        allowUpdates: true

